
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Image image1;
	private global::Gtk.Image image2;
	private global::Gtk.Image image3;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Image image1_2;
	private global::Gtk.Image image2_2;
	private global::Gtk.Image image3_2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Image image1_3;
	private global::Gtk.Image image2_3;
	private global::Gtk.Image image3_3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.ToggleButton togglebutton1;
	private global::Gtk.Button button2;
	private global::Gtk.ToggleButton togglebutton2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Image Importer");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.vbox7.Add (this.image1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image ();
		this.image2.Name = "image2";
		this.vbox7.Add (this.image2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.image3 = new global::Gtk.Image ();
		this.image3.Name = "image3";
		this.vbox7.Add (this.image3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox3.Add (this.vbox7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox7]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.image1_2 = new global::Gtk.Image ();
		this.image1_2.Name = "image1_2";
		this.vbox6.Add (this.image1_2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image1_2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.image2_2 = new global::Gtk.Image ();
		this.image2_2.Name = "image2_2";
		this.vbox6.Add (this.image2_2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image2_2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.image3_2 = new global::Gtk.Image ();
		this.image3_2.Name = "image3_2";
		this.vbox6.Add (this.image3_2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image3_2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox3.Add (this.vbox6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox6]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.image1_3 = new global::Gtk.Image ();
		this.image1_3.Name = "image1_3";
		this.vbox5.Add (this.image1_3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image1_3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.image2_3 = new global::Gtk.Image ();
		this.image2_3.Name = "image2_3";
		this.vbox5.Add (this.image2_3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image2_3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.image3_3 = new global::Gtk.Image ();
		this.image3_3.Name = "image3_3";
		this.vbox5.Add (this.image3_3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image3_3]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox5]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.togglebutton1 = new global::Gtk.ToggleButton ();
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("On/Off");
		this.hbox4.Add (this.togglebutton1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.togglebutton1]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Get Graph");
		this.hbox4.Add (this.button2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button2]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.togglebutton2 = new global::Gtk.ToggleButton ();
		this.togglebutton2.CanFocus = true;
		this.togglebutton2.Name = "togglebutton2";
		this.togglebutton2.UseUnderline = true;
		this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
		this.hbox4.Add (this.togglebutton2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.togglebutton2]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.togglebutton1.Toggled += new global::System.EventHandler (this.On_Off_Toogled);
		this.button2.Clicked += new global::System.EventHandler (this.GraphLoader);
	}
}
