
// This file has been generated by the GUI designer. Do not modify.
namespace AquaControl
{
	public partial class Preferences
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label xivelyFeedLabel;
		private global::Gtk.Entry xivelyFeedIdEntry;
		private global::Gtk.Label xivelyApiLabel;
		private global::Gtk.Entry xivelyApiKeyEntry;
		private global::Gtk.Label impKeyLabel;
		private global::Gtk.Entry impKeyEntry;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Button save;
		private global::Gtk.Label statusLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AquaControl.Preferences
			this.Name = "AquaControl.Preferences";
			this.Title = global::Mono.Unix.Catalog.GetString ("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(15));
			// Container child AquaControl.Preferences.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.xivelyFeedLabel = new global::Gtk.Label ();
			this.xivelyFeedLabel.Name = "xivelyFeedLabel";
			this.xivelyFeedLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Xively Feed Id:");
			this.vbox1.Add (this.xivelyFeedLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.xivelyFeedLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.xivelyFeedIdEntry = new global::Gtk.Entry ();
			this.xivelyFeedIdEntry.CanFocus = true;
			this.xivelyFeedIdEntry.Name = "xivelyFeedIdEntry";
			this.xivelyFeedIdEntry.IsEditable = true;
			this.xivelyFeedIdEntry.InvisibleChar = '●';
			this.vbox1.Add (this.xivelyFeedIdEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.xivelyFeedIdEntry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.xivelyApiLabel = new global::Gtk.Label ();
			this.xivelyApiLabel.Name = "xivelyApiLabel";
			this.xivelyApiLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Xively Api Key:");
			this.vbox1.Add (this.xivelyApiLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.xivelyApiLabel]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.xivelyApiKeyEntry = new global::Gtk.Entry ();
			this.xivelyApiKeyEntry.CanFocus = true;
			this.xivelyApiKeyEntry.Name = "xivelyApiKeyEntry";
			this.xivelyApiKeyEntry.IsEditable = true;
			this.xivelyApiKeyEntry.InvisibleChar = '●';
			this.vbox1.Add (this.xivelyApiKeyEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.xivelyApiKeyEntry]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.impKeyLabel = new global::Gtk.Label ();
			this.impKeyLabel.Name = "impKeyLabel";
			this.impKeyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Imp Api Key:");
			this.vbox1.Add (this.impKeyLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.impKeyLabel]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.impKeyEntry = new global::Gtk.Entry ();
			this.impKeyEntry.CanFocus = true;
			this.impKeyEntry.Name = "impKeyEntry";
			this.impKeyEntry.IsEditable = true;
			this.impKeyEntry.InvisibleChar = '●';
			this.vbox1.Add (this.impKeyEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.impKeyEntry]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.save = new global::Gtk.Button ();
			this.save.CanFocus = true;
			this.save.Name = "save";
			this.save.UseUnderline = true;
			this.save.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.vbox1.Add (this.save);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.save]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusLabel = new global::Gtk.Label ();
			this.statusLabel.Name = "statusLabel";
			this.vbox1.Add (this.statusLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusLabel]));
			w9.Position = 8;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.save.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		}
	}
}
