
// This file has been generated by the GUI designer. Do not modify.
namespace AquaControl
{
	public partial class PointDot
	{
		public virtual void Build ()
		{
			// Action group AquaControl.PointDot
		}
	}
}
