
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label7;
	private global::Gtk.Label label8;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label9;
	private global::Gtk.Label label10;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label11;
	private global::Gtk.Label label12;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label13;
	private global::Gtk.Label label14;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label15;
	private global::Gtk.Label label16;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label label17;
	private global::Gtk.Label label18;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label19;
	private global::Gtk.Label label20;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label21;
	private global::Gtk.Label label22;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label23;
	private global::Gtk.Label label24;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label label25;
	private global::Gtk.Label label26;
	private global::Gtk.HBox hbox14;
	private global::Gtk.Label label27;
	private global::Gtk.Label label28;
	private global::Gtk.HBox hbox15;
	private global::Gtk.Label label29;
	private global::Gtk.Label label30;
	private global::Gtk.Button getDataButton;
	private global::Gtk.Button prefButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.hbox8.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.hbox8.Add (this.label2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox4.Add (this.hbox8);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
		this.hbox7.Add (this.label7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label7]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
		this.hbox7.Add (this.label8);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label8]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox4.Add (this.hbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
		this.hbox6.Add (this.label9);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
		this.hbox6.Add (this.label10);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label10]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox4.Add (this.hbox6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("label11");
		this.hbox3.Add (this.label11);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label11]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("label12");
		this.hbox3.Add (this.label12);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label12]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("label13");
		this.hbox2.Add (this.label13);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label13]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("label14");
		this.hbox2.Add (this.label14);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label14]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("label15");
		this.hbox1.Add (this.label15);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label15]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("label16");
		this.hbox1.Add (this.label16);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label16]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("label17");
		this.hbox9.Add (this.label17);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label17]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("label18");
		this.hbox9.Add (this.label18);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label18]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox1.Add (this.hbox9);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("label19");
		this.hbox10.Add (this.label19);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label19]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("label20");
		this.hbox10.Add (this.label20);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label20]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox1.Add (this.hbox10);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox10]));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("label21");
		this.hbox11.Add (this.label21);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label21]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("label22");
		this.hbox11.Add (this.label22);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label22]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox1.Add (this.hbox11);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox11]));
		w29.Position = 4;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label23 = new global::Gtk.Label ();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("label23");
		this.hbox12.Add (this.label23);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label23]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label ();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("label24");
		this.hbox12.Add (this.label24);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label24]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		this.vbox1.Add (this.hbox12);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox12]));
		w32.Position = 5;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("label25");
		this.hbox13.Add (this.label25);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label25]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label26 = new global::Gtk.Label ();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("label26");
		this.hbox13.Add (this.label26);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label26]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox1.Add (this.hbox13);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox13]));
		w35.Position = 6;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label27 = new global::Gtk.Label ();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("label27");
		this.hbox14.Add (this.label27);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label27]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label28 = new global::Gtk.Label ();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("label28");
		this.hbox14.Add (this.label28);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label28]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox1.Add (this.hbox14);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox14]));
		w38.Position = 7;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label29 = new global::Gtk.Label ();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("label29");
		this.hbox15.Add (this.label29);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label29]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label30 = new global::Gtk.Label ();
		this.label30.Name = "label30";
		this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("label30");
		this.hbox15.Add (this.label30);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label30]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox1.Add (this.hbox15);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox15]));
		w41.Position = 8;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.getDataButton = new global::Gtk.Button ();
		this.getDataButton.CanFocus = true;
		this.getDataButton.Name = "getDataButton";
		this.getDataButton.UseUnderline = true;
		this.getDataButton.Label = global::Mono.Unix.Catalog.GetString ("Get Data");
		this.vbox1.Add (this.getDataButton);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.getDataButton]));
		w42.Position = 9;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.prefButton = new global::Gtk.Button ();
		this.prefButton.CanFocus = true;
		this.prefButton.Name = "prefButton";
		this.prefButton.UseUnderline = true;
		this.prefButton.Label = global::Mono.Unix.Catalog.GetString ("Preferences");
		this.vbox1.Add (this.prefButton);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.prefButton]));
		w43.Position = 12;
		w43.Expand = false;
		w43.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 456;
		this.DefaultHeight = 382;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.getDataButton.Clicked += new global::System.EventHandler (this.OnButtonGetDataClicked);
		this.prefButton.Clicked += new global::System.EventHandler (this.OnPrefButtonClicked);
	}
}
