
// This file has been generated by the GUI designer. Do not modify.
namespace xively_test
{
	public partial class Preferences
	{
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label labelAPI;
		private global::Gtk.Entry APIentry;
		private global::Gtk.Button button2;
		private global::Gtk.Label savedAPIKey;
		private global::Gtk.Button close;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xively_test.Preferences
			this.Name = "xively_test.Preferences";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child xively_test.Preferences.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.labelAPI = new global::Gtk.Label ();
			this.labelAPI.Name = "labelAPI";
			this.labelAPI.LabelProp = global::Mono.Unix.Catalog.GetString ("API KEY:");
			this.vbox5.Add (this.labelAPI);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.labelAPI]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.APIentry = new global::Gtk.Entry ();
			this.APIentry.CanFocus = true;
			this.APIentry.Name = "APIentry";
			this.APIentry.IsEditable = true;
			this.APIentry.InvisibleChar = '●';
			this.vbox5.Add (this.APIentry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.APIentry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.vbox5.Add (this.button2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.savedAPIKey = new global::Gtk.Label ();
			this.savedAPIKey.Name = "savedAPIKey";
			this.savedAPIKey.LabelProp = global::Mono.Unix.Catalog.GetString ("using:");
			this.vbox5.Add (this.savedAPIKey);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.savedAPIKey]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.close = new global::Gtk.Button ();
			this.close.CanFocus = true;
			this.close.Name = "close";
			this.close.UseUnderline = true;
			this.close.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.vbox5.Add (this.close);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.close]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.close.Clicked += new global::System.EventHandler (this.OnCloseClicked);
		}
	}
}
