
// This file has been generated by the GUI designer. Do not modify.
namespace xively_test
{
	public partial class G1
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.Image imgSpace;
		private global::Gtk.Button button18;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xively_test.G1
			this.Name = "xively_test.G1";
			this.Title = global::Mono.Unix.Catalog.GetString ("G1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child xively_test.G1.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.imgSpace = new global::Gtk.Image ();
			this.imgSpace.Name = "imgSpace";
			this.imgSpace.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.vbox6.Add (this.imgSpace);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.imgSpace]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			this.button18.UseUnderline = true;
			this.button18.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.vbox6.Add (this.button18);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button18]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 949;
			this.DefaultHeight = 579;
			this.Show ();
			this.button18.Clicked += new global::System.EventHandler (this.OnButton18Clicked);
		}
	}
}
